#!/usr/bin/env bash
set -euo pipefail

readonly test_root=$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
readonly setup_script="$test_root/Scripts/setup-swift-tools.sh"
readonly runner="$test_root/bin/swift-tooling"
readonly release_builder="$test_root/Scripts/build-release.sh"
readonly mintfile_generator="$test_root/Scripts/generate-mintfile.sh"
readonly toolchain_lock_parser="$test_root/Scripts/toolchain-lock.sh"
readonly test_temp_root=$(mktemp -d "${TMPDIR:-/tmp}/swift-tooling-tests.XXXXXX")

cleanup() {
    rm -rf "$test_temp_root"
}

trap cleanup EXIT

failures=0

fail() {
    printf 'FAIL: %s\n' "$1" >&2
    failures=$((failures + 1))
}

assert_file_exists() {
    if [[ ! -f "$1" ]]; then
        fail "expected file to exist: $1"
    fi
}

assert_file_not_exists() {
    if [[ -e "$1" ]]; then
        fail "expected path not to exist: $1"
    fi
}

assert_contains() {
    local file=$1
    local expected=$2
    if ! grep -Fq -- "$expected" "$file"; then
        fail "expected '$expected' in $file"
    fi
}

assert_order() {
    local file=$1
    local first=$2
    local second=$3
    local first_line second_line
    first_line=$(grep -Fn -- "$first" "$file" | head -n 1 | cut -d: -f1 || true)
    second_line=$(grep -Fn -- "$second" "$file" | head -n 1 | cut -d: -f1 || true)
    if [[ -z "$first_line" || -z "$second_line" || "$first_line" -ge "$second_line" ]]; then
        fail "expected '$first' before '$second' in $file"
    fi
}

assert_equal() {
    if [[ "$1" != "$2" ]]; then
        fail "expected '$1' to equal '$2'"
    fi
}

new_fixture() {
    local fixture
    fixture=$(mktemp -d "$test_temp_root/fixture.XXXXXX")
    mkdir -p "$fixture/consumer/Scripts" "$fixture/consumer/Sources" "$fixture/consumer/Tests"
    printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$fixture/consumer/Scripts/with-xcode.sh"
    printf '%s\n' 'source-root' > "$fixture/consumer/Sources/Example.swift"
    printf '%s\n' 'test-root' > "$fixture/consumer/Tests/ExampleTests.swift"
    printf '%s\n' '# local swiftformat options' > "$fixture/consumer/.swiftformat"
    printf '%s\n' '# local swiftlint options' > "$fixture/consumer/.swiftlint.yml"
    printf '%s\n' '# generated by the consumer' > "$fixture/consumer/.gitignore"
    printf '%s\n' "$fixture"
}

new_release_archive() {
    local fixture=$1
    local version=$2
    local release_root="$fixture/release"
    local archive="$fixture/swift-tooling-$version.tar.gz"

    mkdir -p "$release_root/bin" "$release_root/config" "$release_root/Scripts"
    printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$release_root/bin/swift-tooling"
    printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$release_root/Scripts/setup-swift-tools.sh"
    printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$release_root/Scripts/swift-tools.sh"
    cp "$test_root/Scripts/toolchain-lock.sh" "$release_root/Scripts/toolchain-lock.sh"
    printf '%s\n' '# local configuration template' > "$release_root/Scripts/swift-tools-local.sh"
    printf '%s\n' 'base format' > "$release_root/config/swiftformat.base"
    printf '%s\n' 'base lint' > "$release_root/config/swiftlint.base.yml"
    printf '%s\n' 'MINT_VERSION=0.18.0' > "$release_root/toolchain.lock"
    printf '%s\n' 'nicklockwood/SwiftFormat@0.63.0' 'realm/SwiftLint@0.65.1' > "$release_root/Mintfile"
    chmod 0755 "$release_root/bin/swift-tooling" "$release_root/Scripts/setup-swift-tools.sh" \
        "$release_root/Scripts/swift-tools.sh"
    tar -czf "$archive" -C "$release_root" .
    shasum -a 256 "$archive" | awk '{print $1}'
}

new_unsafe_release_archive() {
    local fixture=$1
    local version=$2
    local archive="$fixture/swift-tooling-$version-unsafe.tar.gz"

    new_release_archive "$fixture" "$version" >/dev/null
    printf '%s\n' 'outside release root' > "$fixture/outside-release-root"
    ln -s "$fixture/outside-release-root" "$fixture/release/unsafe-link"
    tar -czf "$archive" -C "$fixture/release" .
    shasum -a 256 "$archive" | awk '{print $1}'
}

new_mint_archive() {
    local fixture=$1
    local archive_kind=${2:-valid}
    local mint_source="$fixture/mint-source"
    local mint_archive="$fixture/mint.zip"
    local mint_sha

    mkdir -p "$fixture/release/Scripts" "$mint_source"
    cp "$test_root/Scripts/toolchain-lock.sh" "$fixture/release/Scripts/toolchain-lock.sh"
    printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$mint_source/mint"
    if [[ "$archive_kind" = unsafe ]]; then
        printf '%s\n' 'outside mint archive' > "$fixture/outside-mint-archive"
        ln -s "$fixture/outside-mint-archive" "$mint_source/unsafe-link"
        (cd "$mint_source" && zip -q -y "$mint_archive" mint unsafe-link)
    else
        (cd "$mint_source" && zip -q "$mint_archive" mint)
    fi
    mint_sha=$(shasum -a 256 "$mint_archive" | awk '{print $1}')
    printf '%s\n' \
        'MINT_VERSION=0.18.0' \
        "MINT_ARCHIVE_URL=file://$mint_archive" \
        "MINT_ARCHIVE_SHA256=$mint_sha" \
        'SWIFTFORMAT_PACKAGE=nicklockwood/SwiftFormat' \
        'SWIFTFORMAT_VERSION=0.63.0' \
        'SWIFTLINT_PACKAGE=realm/SwiftLint' \
        'SWIFTLINT_VERSION=0.65.1' > "$fixture/release/toolchain.lock"
    printf '%s\n' 'nicklockwood/SwiftFormat@0.63.0' 'realm/SwiftLint@0.65.1' > "$fixture/release/Mintfile"
    printf '%s\n' "$mint_sha"
}

test_setup_installs_and_is_idempotent() {
    local fixture archive_sha archive consumer
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    archive_sha=$(new_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0.tar.gz"

    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha"; then
        fail 'initial setup should succeed'
        return
    fi

    assert_file_exists "$consumer/.tools/swift-tooling/v1.0.0/bin/swift-tooling"
    assert_file_exists "$consumer/Scripts/swift-tools.sh"
    assert_file_exists "$consumer/Scripts/swift-tools.lock"
    assert_file_exists "$consumer/Scripts/swift-tools-local.sh"
    assert_contains "$consumer/.gitignore" '.tools/'
    assert_contains "$consumer/Scripts/swift-tools.lock" \
        'SWIFT_TOOLING_RELEASE_ASSET=swift-tooling-v1.0.0.tar.gz'

    local adapter_before lock_before local_before ignore_before
    adapter_before=$(shasum -a 256 "$consumer/Scripts/swift-tools.sh")
    lock_before=$(shasum -a 256 "$consumer/Scripts/swift-tools.lock")
    ignore_before=$(shasum -a 256 "$consumer/.gitignore")
    printf '%s\n' '# user customization' >> "$consumer/Scripts/swift-tools-local.sh"
    local_before=$(shasum -a 256 "$consumer/Scripts/swift-tools-local.sh")

    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha"; then
        fail 'repeated setup should succeed'
        return
    fi

    assert_equal "$adapter_before" "$(shasum -a 256 "$consumer/Scripts/swift-tools.sh")"
    assert_equal "$lock_before" "$(shasum -a 256 "$consumer/Scripts/swift-tools.lock")"
    assert_equal "$local_before" "$(shasum -a 256 "$consumer/Scripts/swift-tools-local.sh")"
    assert_equal "$ignore_before" "$(shasum -a 256 "$consumer/.gitignore")"
    assert_equal 1 "$(grep -Fc '.tools/' "$consumer/.gitignore")"
}

test_setup_rejects_checksum_mismatch_without_partial_install() {
    local fixture archive consumer
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    new_release_archive "$fixture" v1.0.0 >/dev/null
    archive="$fixture/swift-tooling-v1.0.0.tar.gz"

    if bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 wrong; then
        fail 'checksum mismatch should fail'
    fi

    assert_file_not_exists "$consumer/.tools/swift-tooling/v1.0.0"
    assert_file_not_exists "$consumer/Scripts/swift-tools.sh"
    assert_file_not_exists "$consumer/Scripts/swift-tools.lock"
}

test_setup_rejects_unsafe_release_version() {
    local fixture consumer archive_sha archive
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    archive_sha=$(new_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0.tar.gz"

    if bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version ../escape \
        --release-sha256 "$archive_sha"; then
        fail 'unsafe release version should fail'
    fi

    assert_file_not_exists "$fixture/escape"
    assert_file_not_exists "$consumer/.tools/escape"
}

test_setup_rejects_unsafe_archive_entries() {
    local fixture consumer archive_sha archive
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    archive_sha=$(new_unsafe_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0-unsafe.tar.gz"

    if bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha"; then
        fail 'unsafe archive entries should fail setup'
    fi

    assert_file_not_exists "$consumer/.tools/swift-tooling/v1.0.0"
    assert_file_exists "$fixture/outside-release-root"
}

test_runner_bootstrap_does_not_require_consumer_paths_or_configs() {
    local fixture consumer fake_mint log
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    mkdir -p "$fixture/release/Scripts"
    cp "$test_root/Scripts/toolchain-lock.sh" "$fixture/release/Scripts/toolchain-lock.sh"
    printf '%s\n' \
        'MINT_VERSION=0.18.0' \
        'SWIFTFORMAT_PACKAGE=nicklockwood/SwiftFormat' \
        'SWIFTFORMAT_VERSION=0.63.0' \
        'SWIFTLINT_PACKAGE=realm/SwiftLint' \
        'SWIFTLINT_VERSION=0.65.1' > "$fixture/release/toolchain.lock"
    printf '%s\n' 'nicklockwood/SwiftFormat@0.63.0' 'realm/SwiftLint@0.65.1' > "$fixture/release/Mintfile"
    fake_mint="$fixture/fake-mint"
    log="$fixture/mint.log"
    cat > "$fake_mint" <<'FAKE_MINT'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${FAKE_MINT_LOG:?}"
FAKE_MINT
    chmod 0755 "$fake_mint"

    if ! FAKE_MINT_LOG="$log" SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$runner" --root "$consumer" --release-root "$fixture/release" bootstrap; then
        fail 'bootstrap should not validate consumer source paths or overlays'
        return
    fi

    assert_contains "$log" 'bootstrap --mintfile'
}

test_runner_accepts_valid_mint_archive() {
    local fixture consumer
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    new_mint_archive "$fixture" >/dev/null

    if ! bash "$runner" --root "$consumer" --release-root "$fixture/release" bootstrap; then
        fail 'valid Mint archives should pass bootstrap validation'
        return
    fi

    assert_file_exists "$consumer/.tools/mint/0.18.0/mint"
}

test_runner_rejects_unsafe_mint_archive() {
    local fixture consumer mint_archive
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    mint_archive="$fixture/mint.zip"
    new_mint_archive "$fixture" unsafe >/dev/null

    if bash "$runner" --root "$consumer" --release-root "$fixture/release" bootstrap; then
        fail 'unsafe Mint archive entries should fail bootstrap'
    fi

    assert_file_not_exists "$consumer/.tools/mint/0.18.0/mint"
    assert_file_not_exists "$consumer/outside-mint-archive"
}

test_runner_forwards_config_and_paths_and_cleans_effective_format_config() {
    local fixture consumer fake_mint log config_log effective_count
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    mkdir -p "$consumer/.tools/mint/bin" "$fixture/release/bin" "$fixture/release/config" \
        "$fixture/release/Scripts"
    cp "$test_root/Scripts/toolchain-lock.sh" "$fixture/release/Scripts/toolchain-lock.sh"
    printf '%s\n' 'mint base' > "$fixture/release/Mintfile"
    printf '%s\n' 'swiftformat base' > "$fixture/release/config/swiftformat.base"
    printf '%s\n' 'swiftlint base' > "$fixture/release/config/swiftlint.base.yml"
    printf '%s\n' 'MINT_VERSION=0.18.0' 'SWIFTFORMAT_PACKAGE=nicklockwood/SwiftFormat' \
        'SWIFTFORMAT_VERSION=0.63.0' 'SWIFTLINT_PACKAGE=realm/SwiftLint' \
        'SWIFTLINT_VERSION=0.65.1' > "$fixture/release/toolchain.lock"
    fake_mint="$fixture/fake-mint"
    log="$fixture/mint.log"
    config_log="$fixture/config.log"
    cat > "$fake_mint" <<'FAKE_MINT'
#!/usr/bin/env bash
set -euo pipefail
args=("$@")
printf '%s\n' "$*" >> "${FAKE_MINT_LOG:?}"
for ((index = 0; index < ${#args[@]}; index += 1)); do
    if [[ "${args[index]}" = --config ]]; then
        printf '%s\n' '--- CONFIG ---' >> "${FAKE_MINT_CONFIG_LOG:?}"
        cat "${args[index + 1]}" >> "${FAKE_MINT_CONFIG_LOG:?}"
    fi
done
exit 0
FAKE_MINT
    chmod +x "$fake_mint"
    cat > "$consumer/Scripts/swift-tools-local.sh" <<'LOCAL_CONFIG'
SWIFT_TOOLS_SOURCE_PATHS=(Sources Tests)
SWIFT_TOOLS_SWIFTFORMAT_CONFIG=.swiftformat
SWIFT_TOOLS_SWIFTLINT_CONFIG=.swiftlint.yml
SWIFT_TOOLS_COMMAND_PREFIX=()
LOCAL_CONFIG

    if ! FAKE_MINT_LOG="$log" FAKE_MINT_CONFIG_LOG="$config_log" \
        SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$runner" --root "$consumer" --release-root "$fixture/release" format; then
        fail 'format should succeed with the fake Mint executable'
        return
    fi

    assert_contains "$log" 'nicklockwood/SwiftFormat@0.63.0'
    assert_contains "$config_log" 'swiftformat base'
    assert_contains "$config_log" '# local swiftformat options'
    assert_order "$config_log" 'swiftformat base' '# local swiftformat options'
    effective_count=$(find "$consumer" -maxdepth 1 -name '.swiftformat.effective.*' -type f | wc -l | tr -d ' ')
    assert_equal 0 "$effective_count"

    : > "$log"
    : > "$config_log"
    if ! FAKE_MINT_LOG="$log" FAKE_MINT_CONFIG_LOG="$config_log" \
        SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$runner" --root "$consumer" --release-root "$fixture/release" lint; then
        fail 'lint should succeed with the fake Mint executable'
        return
    fi

    assert_contains "$log" 'realm/SwiftLint@0.65.1'
    assert_contains "$config_log" 'swiftlint base'
    assert_contains "$config_log" '# local swiftlint options'
    assert_order "$config_log" 'swiftlint base' '# local swiftlint options'
    assert_contains "$log" 'Sources'
    assert_contains "$log" 'Tests'
}

test_runner_requires_local_configuration() {
    local fixture consumer
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    mkdir -p "$fixture/release/Scripts"
    cp "$test_root/Scripts/toolchain-lock.sh" "$fixture/release/Scripts/toolchain-lock.sh"
    printf '%s\n' 'MINT_VERSION=0.18.0' > "$fixture/release/toolchain.lock"
    printf '%s\n' 'SWIFT_TOOLS_SOURCE_PATHS=(Sources)' > "$consumer/Scripts/swift-tools-local.sh"
    rm "$consumer/Scripts/swift-tools-local.sh"

    if bash "$runner" --root "$consumer" --release-root "$fixture/release" lint 2>/dev/null; then
        fail 'runner should reject a missing local configuration'
    fi
}

test_setup_updates_pin_without_overwriting_local_configuration() {
    local fixture consumer archive_sha archive
    fixture=$(new_fixture)
    consumer="$fixture/consumer"

    archive_sha=$(new_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0.tar.gz"
    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha" >/dev/null; then
        fail 'initial pin setup should succeed'
        return
    fi
    printf '%s\n' '# preserve this file' >> "$consumer/Scripts/swift-tools-local.sh"

    archive_sha=$(new_release_archive "$fixture" v1.1.0)
    archive="$fixture/swift-tooling-v1.1.0.tar.gz"
    bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.1.0 \
        --release-sha256 "$archive_sha" >/dev/null

    assert_contains "$consumer/Scripts/swift-tools.lock" 'SWIFT_TOOLING_RELEASE_VERSION=v1.1.0'
    assert_contains "$consumer/Scripts/swift-tools-local.sh" '# preserve this file'
    assert_file_exists "$consumer/.tools/swift-tooling/v1.1.0/bin/swift-tooling"
}

test_setup_refreshes_adapter_when_release_checksum_changes() {
    local fixture consumer archive archive_sha
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    archive_sha=$(new_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0.tar.gz"

    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha" >/dev/null; then
        fail 'initial checksum-change setup should succeed'
        return
    fi

    printf '%s\n' '# refreshed adapter' >> "$fixture/release/Scripts/swift-tools.sh"
    tar -czf "$archive" -C "$fixture/release" .
    archive_sha=$(shasum -a 256 "$archive" | awk '{print $1}')

    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha" >/dev/null; then
        fail 'same-version changed-checksum setup should succeed'
        return
    fi

    assert_contains "$consumer/Scripts/swift-tools.sh" '# refreshed adapter'
}

test_consumer_adapter_delegates_to_pinned_release() {
    local fixture output consumer archive archive_sha fake_mint log
    fixture=$(new_fixture)
    output="$fixture/dist"
    consumer="$fixture/consumer"
    if ! bash "$release_builder" v1.0.0 "$output" >/dev/null; then
        fail 'adapter fixture release should build'
        return
    fi

    archive="$output/swift-tooling-v1.0.0.tar.gz"
    archive_sha=$(shasum -a 256 "$archive" | awk '{print $1}')
    cp "$test_root/Scripts/swift-tools.sh" "$consumer/Scripts/swift-tools.sh"
    chmod 0755 "$consumer/Scripts/swift-tools.sh"
    cat > "$consumer/Scripts/swift-tools.lock" <<'LOCK'
SWIFT_TOOLING_REPOSITORY_URL=https://example.invalid/swift-tooling
SWIFT_TOOLING_RELEASE_VERSION=v1.0.0
SWIFT_TOOLING_RELEASE_SHA256=ARCHIVE_SHA256
SWIFT_TOOLING_RELEASE_ASSET=swift-tooling-v1.0.0.tar.gz
LOCK
    sed -i '' "s/ARCHIVE_SHA256/$archive_sha/" "$consumer/Scripts/swift-tools.lock"
    cat > "$consumer/Scripts/swift-tools-local.sh" <<'LOCAL_CONFIG'
SWIFT_TOOLS_SOURCE_PATHS=(Sources Tests)
SWIFT_TOOLS_SWIFTFORMAT_CONFIG=.swiftformat
SWIFT_TOOLS_SWIFTLINT_CONFIG=.swiftlint.yml
SWIFT_TOOLS_COMMAND_PREFIX=()
LOCAL_CONFIG
    fake_mint="$fixture/fake-mint"
    log="$fixture/mint.log"
    cat > "$fake_mint" <<'FAKE_MINT'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${FAKE_MINT_LOG:?}"
FAKE_MINT
    chmod 0755 "$fake_mint"

    if ! FAKE_MINT_LOG="$log" \
        SWIFT_TOOLING_RELEASE_ROOT="$fixture/installed" \
        SWIFT_TOOLING_RELEASE_ARCHIVE="$archive" \
        SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$consumer/Scripts/swift-tools.sh" exec swiftlint lint; then
        fail 'consumer adapter should delegate to the pinned release'
        return
    fi

    assert_contains "$log" 'realm/SwiftLint@0.65.1'
}

test_consumer_adapter_rejects_unsafe_archive_entries() {
    local fixture consumer archive_sha archive
    fixture=$(new_fixture)
    consumer="$fixture/consumer"
    archive_sha=$(new_unsafe_release_archive "$fixture" v1.0.0)
    archive="$fixture/swift-tooling-v1.0.0-unsafe.tar.gz"
    cp "$test_root/Scripts/swift-tools.sh" "$consumer/Scripts/swift-tools.sh"
    chmod 0755 "$consumer/Scripts/swift-tools.sh"
    cat > "$consumer/Scripts/swift-tools.lock" <<LOCK
SWIFT_TOOLING_REPOSITORY_URL=https://example.invalid/swift-tooling
SWIFT_TOOLING_RELEASE_VERSION=v1.0.0
SWIFT_TOOLING_RELEASE_SHA256=$archive_sha
SWIFT_TOOLING_RELEASE_ASSET=swift-tooling-v1.0.0-unsafe.tar.gz
LOCK

    if SWIFT_TOOLING_RELEASE_ROOT="$fixture/installed" \
        SWIFT_TOOLING_RELEASE_ARCHIVE="$archive" \
        bash "$consumer/Scripts/swift-tools.sh" exec swiftlint lint; then
        fail 'unsafe archive entries should fail in the consumer adapter'
    fi

    assert_file_not_exists "$fixture/installed"
    assert_file_exists "$fixture/outside-release-root"
}

test_release_builder_creates_verified_release_assets() {
    local fixture output archive archive_sha
    fixture=$(mktemp -d "$test_temp_root/fixture.XXXXXX")
    output="$fixture/dist"

    if ! bash "$release_builder" v1.0.0 "$output"; then
        fail 'release builder should succeed'
        return
    fi

    archive="$output/swift-tooling-v1.0.0.tar.gz"
    archive_sha=$(shasum -a 256 "$archive" | awk '{print $1}')
    assert_file_exists "$archive"
    assert_file_exists "$archive.sha256"
    assert_file_exists "$output/setup-swift-tools.sh"
    assert_file_exists "$output/release-manifest.env"
    assert_contains "$output/release-manifest.env" 'RELEASE_VERSION=v1.0.0'
    assert_contains "$output/release-manifest.env" "RELEASE_SHA256=$archive_sha"
    assert_contains "$output/release-manifest.env" 'RELEASE_ASSET=swift-tooling-v1.0.0.tar.gz'
    if ! tar -xOf "$archive" ./Mintfile | grep -Fq 'nicklockwood/SwiftFormat@0.63.0'; then
        fail 'release Mintfile should be generated from toolchain.lock'
    fi
    if ! tar -xOf "$archive" ./Mintfile | grep -Fq 'realm/SwiftLint@0.65.1'; then
        fail 'release Mintfile should include the pinned SwiftLint package'
    fi
}

test_mintfile_generator_follows_lock_shell_semantics() {
    local fixture lock output
    fixture=$(new_fixture)
    lock="$fixture/toolchain.lock"
    output="$fixture/Mintfile"
    cat > "$lock" <<'LOCK'
MINT_VERSION=0.18.0
SWIFTFORMAT_PACKAGE=wrong/SwiftFormat
export SWIFTFORMAT_PACKAGE='nicklockwood/SwiftFormat'
export SWIFTFORMAT_VERSION="0.63.0" # inline comment
SWIFTLINT_PACKAGE='realm/SwiftLint'
SWIFTLINT_VERSION=0.65\.1 # inline comment
LOCK

    if ! bash "$mintfile_generator" "$lock" "$output"; then
        fail 'Mintfile generation should accept quoted and repeated lock assignments'
        return
    fi

    assert_contains "$output" 'nicklockwood/SwiftFormat@0.63.0'
    assert_contains "$output" 'realm/SwiftLint@0.65.1'
    if grep -Fq 'wrong/SwiftFormat' "$output"; then
        fail 'Mintfile generation should use the last lock assignment'
    fi
}

test_toolchain_lock_parser_supports_escaped_quoted_values() {
    local fixture lock parsed
    fixture=$(new_fixture)
    lock="$fixture/toolchain.lock"
    cat > "$lock" <<'LOCK'
export MINT_ARCHIVE_URL="https://example.com/mint.zip\"?channel=stable"
LOCK

    if ! parsed=$(bash -c 'source "$1"; toolchain_lock_value "$2" MINT_ARCHIVE_URL' \
        _ "$toolchain_lock_parser" "$lock"); then
        fail 'parsing an escaped quoted lock value should succeed'
        return
    fi
    assert_equal 'https://example.com/mint.zip"?channel=stable' "$parsed"
}

test_built_release_installs_and_runs_through_consumer_adapter() {
    local fixture output consumer archive archive_sha fake_mint log effective_count
    fixture=$(new_fixture)
    output="$fixture/dist"
    consumer="$fixture/consumer"

    if ! bash "$release_builder" v1.0.0 "$output" >/dev/null; then
        fail 'a built release should be installable'
        return
    fi

    archive="$output/swift-tooling-v1.0.0.tar.gz"
    archive_sha=$(shasum -a 256 "$archive" | awk '{print $1}')
    if ! bash "$setup_script" \
        --repository-root "$consumer" \
        --release-archive "$archive" \
        --release-version v1.0.0 \
        --release-sha256 "$archive_sha" \
        --release-asset "$(basename "$archive")" >/dev/null; then
        fail 'a built release should install successfully'
        return
    fi

    cat > "$consumer/Scripts/swift-tools-local.sh" <<'LOCAL_CONFIG'
SWIFT_TOOLS_SOURCE_PATHS=(Sources Tests)
SWIFT_TOOLS_SWIFTFORMAT_CONFIG=.swiftformat
SWIFT_TOOLS_SWIFTLINT_CONFIG=.swiftlint.yml
SWIFT_TOOLS_COMMAND_PREFIX=()
LOCAL_CONFIG

    fake_mint="$fixture/fake-mint"
    log="$fixture/mint.log"
    cat > "$fake_mint" <<'FAKE_MINT'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${FAKE_MINT_LOG:?}"
FAKE_MINT
    chmod 0755 "$fake_mint"

    if ! FAKE_MINT_LOG="$log" SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$consumer/Scripts/swift-tools.sh" lint; then
        fail 'the installed release should run through the consumer adapter'
        return
    fi

    assert_contains "$log" 'nicklockwood/SwiftFormat@0.63.0'
    assert_contains "$log" 'realm/SwiftLint@0.65.1'
    effective_count=$(find "$consumer" -maxdepth 1 -name '.swiftformat.effective.*' -type f | wc -l | tr -d ' ')
    assert_equal 0 "$effective_count"

    printf '%s\n' 'corrupted release archive' > \
        "$consumer/.tools/swift-tooling/v1.0.0/.swift-tooling-release.tar.gz"
    if FAKE_MINT_LOG="$log" \
        SWIFT_TOOLING_RELEASE_ARCHIVE="$consumer/.tools/swift-tooling/v1.0.0/.swift-tooling-release.tar.gz" \
        SWIFT_TOOLING_MINT_BINARY="$fake_mint" \
        bash "$consumer/Scripts/swift-tools.sh" exec swiftlint lint; then
        fail 'the consumer adapter should reject a corrupted cached release'
    fi
}

test_setup_installs_and_is_idempotent
test_setup_rejects_checksum_mismatch_without_partial_install
test_setup_rejects_unsafe_release_version
test_setup_rejects_unsafe_archive_entries
test_runner_bootstrap_does_not_require_consumer_paths_or_configs
test_runner_accepts_valid_mint_archive
test_runner_rejects_unsafe_mint_archive
test_runner_forwards_config_and_paths_and_cleans_effective_format_config
test_runner_requires_local_configuration
test_setup_updates_pin_without_overwriting_local_configuration
test_setup_refreshes_adapter_when_release_checksum_changes
test_consumer_adapter_delegates_to_pinned_release
test_consumer_adapter_rejects_unsafe_archive_entries
test_release_builder_creates_verified_release_assets
test_mintfile_generator_follows_lock_shell_semantics
test_toolchain_lock_parser_supports_escaped_quoted_values
test_built_release_installs_and_runs_through_consumer_adapter

if [[ "$failures" -ne 0 ]]; then
    printf '%s test(s) failed.\n' "$failures" >&2
    exit 1
fi

printf '%s\n' 'All swift-tooling tests passed.'
